# Generated by Django 5.1.2 on 2024-10-23 19:35

import chats.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='connect_url',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='chat',
            name='identifier',
            field=models.CharField(default=chats.models.generate_identifier, max_length=8, unique=True),
        ),
    ]
